services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compus-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: compus-nginx
    ports:
      - "8081:80"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
