# Generated by Django 4.1.9 on 2023-10-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='parent',
        ),
        migrations.AddField(
            model_name='service',
            name='subs',
            field=models.ManyToManyField(blank=True, to='base.subservice'),
        ),
    ]
