# Generated by Django 4.1.9 on 2023-11-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_service_description_subservice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='url',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='url',
        ),
    ]
