# Generated by Django 4.2.7 on 2023-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_director_email_numberdata_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='themify-icons name', max_length=255, null=True),
        ),
    ]
