# Generated by Django 4.2.7 on 2023-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('icon', models.CharField(blank=True, help_text='themify-icons name', max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='subs',
            field=models.ManyToManyField(blank=True, to='base.subservice'),
        ),
        migrations.AlterModelTable(
            name='service',
            table='',
        ),
    ]
