# Generated by Django 4.2.7 on 2023-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_homeservice_alter_service_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeService',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='themify-icons name', max_length=255, null=True),
        ),
    ]
