# Generated by Django 4.2.7 on 2023-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_homeservice_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='themify-icons name eg: car, home, user, etc', max_length=255, null=True),
        ),
    ]
