# Generated by Django 4.2.7 on 2023-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_director_facebook_director_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
