# Generated by Django 4.2.7 on 2023-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_director_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='director/'),
        ),
    ]
